apiVersion: apps/v1
kind: Deployment
metadata:
  name: phase1      # e.g., myapp
spec:
  replicas: 1            # number of pods
  selector:
    matchLabels:
      app: phase1
  template:
    metadata:
      labels:
        app: phase1
    spec:
      containers:
      - name: phase1
        imagePullPolicy: Never #This tells Kubernetes donâ€™t try to pull from any registry, only use what exists locally inside the node.
        image: phase1-configmap:latest   # e.g., nginx:latest
        ports:
        - containerPort: 80  # e.g., 80
        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: phase1-config
              key: APP_NAME
        - name: APP_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: phase1-config
              key: APP_MESSAGE