apiVersion: v1
kind: Service
metadata:
  name: phase1
spec:
  type: NodePort        # ClusterIP / NodePort / LoadBalancer
  selector:
    app: phase1
  ports:
  - port: 8080         # exposed port
    targetPort: 80   # port on container
